### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by colramos-amd** [portothree/grafana-mongodb-datasource#22]
I'm using this to enable MongoDB on Grafana and am running into an error when I try to create this panel. I've successfully created other panels, but just started getting this error.

I'm confused because the query works perfectly fine in `VSCode Mongo Playground`, but complains in Grafana...

**The error:**

![](https://i.stack.imgur.com/c2qeW.png)

**My code:**
``` json
db.pmc_top_stats.aggregate([
    {"$group": {
        "_id": "$Name",
        "calls": {
            "$first": "$Calls"
        },
        "totalDur": {
            "$sum": "$TotalDurationNs"
        },
        "avg": {
            "$sum": "$AverageNs"
        },
        "percen": {
            "$sum": "$Percentage"
        }
    }},
    {"$set": {
    "array": [
        {
          "Name": "$_id",
          "Calls": "$calls",
          "Total Duration (ns)": "$totalDur",
          "Avg (ns)": "$avg",
          "Percent (%)": "$percen"
        }
      ]
    }},
    {"$unwind": {
        "path": "$array"
    }},
    {"$replaceRoot": {
        "newRoot": "$array"
    }}
]);
```

**MongoDB Playground Output:** (Shortened)
```json
{
    "Name": "void Koos::Experimental::Impl[clone .kd]",
    "Calls": 1204,
    "Total Duration (ns)": 16620774,
    "Avg (ns)": 13804,
    "Percent (%)": 0.009686363688228965
  },
  {
    "Name": "void Koos::Experimental 1024u, 1u>() [clone .kd]",
    "Calls": 3977,
    "Total Duration (ns)": 807120277,
    "Avg (ns)": 202947,
    "Percent (%)": 0.47037884897334525
  },
```

_Note: I've looked into [solutions](https://stackoverflow.com/questions/56151099/unexpected-end-of-json-input-in-mongodb-compass) and have already tried "minification" of my code. Still get the same error_

Version: v8.2.1

**Comment by portothree** [comment]
@colramos-amd sorry for the delay on this, I have released the new version where this is fixed, although I still want to improve more the query parser (PRs welcome 😁).
